### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by hroncok** [gordonmessmer/pyreq2rpm#1]
Please add a free software license, preferably something permissive. Thanks.

**Comment by gordonmessmer** [comment]
You're right.  It's best to be clear about this from the very beginning.  I've added GPL2 (or later), since that's what's RPM is using currently.

Thank you.

**Comment by hroncok** [comment]
Would you mind to reconsider and add a less strict one? Our pyproject-rpm-macros use MIT:

https://src.fedoraproject.org/rpms/pyproject-rpm-macros/blob/master/f/LICENSE

**Comment by gordonmessmer** [comment]
I don't mind at all.
