### ISSUE TITLE
Prereleases

### ISSUE THREAD

**Issue by hroncok** [gordonmessmer/pyreq2rpm#2]
Python supports pre-releases, such as 1.2.3b5. The current code seems to not handle those.

**Comment by gordonmessmer** [comment]
That's true, and I'd think that we should probably do something in all cases, since it looks like a case where rpm version comparison is different from Python's:

    $ rpmdev-vercmp 2.4.8b5 2.4.8
    2.4.8b5 > 2.4.8

We could always parse the version id and use base_version.  One effect would be that requirements specified as "> 2.4.8b5" would be translated into a requirement on an rpm with a final release number "2.4.8".  In that case, packagers would probably be expected to translate pre-release information into the rpm release field:

    rpmdev-vercmp 2.4.8-1 2.4.8-beta.1
    2.4.8-1 > 2.4.8-beta.1

Would that work?  Or do you have another suggestion?

**Comment by hroncok** [comment]
Maybe we can use \~. Aka translate 2.4.8b1 to 2.4.8\~b1.

**Comment by encukou** [comment]
IMO, `1.1a1` should map to `1.1~a1`
Edit: Oh, that's what Miro suggested, but `~` is ~Markdown~[GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) syntax :)

**Comment by hroncok** [comment]
I have updated my command to escape the tilde.

**Comment by gordonmessmer** [comment]
How do we handle stripping trailing zeros in the case of prereleases?  I would guess that 1.0.0b5 should be translated to `1.0.0~b5` and not to `1~b5` ?

Maybe it doesn't matter...

```
$ rpmdev-vercmp 1.0.0 1~b5
1.0.0 > 1~b5
$ rpmdev-vercmp 1.0.0 1.0.0~b5
1.0.0 > 1.0.0~b5
```

**Comment by hroncok** [comment]
```
$  rpmdev-vercmp 1 1.0.0~b5
1 < 1.0.0~b5
```

IIRC `1.0.0b5` should be translated to `1~b5`.

**Comment by gordonmessmer** [comment]
Are we also concerned about post and dev releases?  I don't think the same translation will work for post.

```
$ rpmdev-vercmp 1.0.0 1.0.0~post1
1.0.0 > 1.0.0~post1
```

**Comment by hroncok** [comment]
In the long run, yes. RPM has `^` for this:

```
$ rpmdev-vercmp 1.0.0 1.0.0^post1
1.0.0 < 1.0.0^post1
```

https://github.com/rpm-software-management/rpm/pull/597

However, it works even without it, so not sure.

**Comment by gordonmessmer** [comment]
I haven't put in the post or dev handling, but I've pushed changes to handle prerelease.

**Comment by gordonmessmer** [comment]
I've added handling for post, and evaluating whether each Requirement is valid in pkg_resources.  The next thing that looks like it needs to be improved is handling ".*' in the ordered comparisons.

**Comment by gordonmessmer** [comment]
I've put in a basic testing framework.  The "tests.py" script still outputs all the previous permutations of operators and versions.  When we believe those are correct, I'll add the rest to the tests.

**Comment by gordonmessmer** [comment]
I've added all of the current results to pytest, as well as running "rpmbuild" to verify that all of the results are valid in builds.

Probably ought to raise an exception for the "invalid version" results, but for now I'm closing this issue.
