### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by encukou** [gordonmessmer/pyreq2rpm#3]
We should be talking about Python Packaging versioning rather than PEP 440.

PEPs 440 and 508 happen to be the current specification, but future revisions will be either new PEPs, or will copy the spec to packaging.python.org and update it there.

**Comment by gordonmessmer** [comment]
We can, I'm not opposed to that at all.  But I envisioned this as a short-lived project to clean up the translations, write tests, and then merge that code into rpm.  If you'd like to to endure as a small external library instead, I can definitely rename it.

**Comment by gordonmessmer** [comment]
I've renamed the project in order to facilitate testing.
